//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pame.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAME is a free Pascal IDE for students. For comments, questions or bugs contact me at: samartzidis@gmail.com..
        /// </summary>
        internal static string AboutBox_String1 {
            get {
                return ResourceManager.GetString("AboutBox_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text &quot;{0}&quot; not found.
        /// </summary>
        internal static string FindAndReplaceForm_String1 {
            get {
                return ResourceManager.GetString("FindAndReplaceForm_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text given to search!.
        /// </summary>
        internal static string FindAndReplaceForm_String10 {
            get {
                return ResourceManager.GetString("FindAndReplaceForm_String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not found.
        /// </summary>
        internal static string FindAndReplaceForm_String11 {
            get {
                return ResourceManager.GetString("FindAndReplaceForm_String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No occurences found.
        /// </summary>
        internal static string FindAndReplaceForm_String12 {
            get {
                return ResourceManager.GetString("FindAndReplaceForm_String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurences were replaced.
        /// </summary>
        internal static string FindAndReplaceForm_String13 {
            get {
                return ResourceManager.GetString("FindAndReplaceForm_String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp; replace.
        /// </summary>
        internal static string FindAndReplaceForm_String6 {
            get {
                return ResourceManager.GetString("FindAndReplaceForm_String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string FindAndReplaceForm_String7 {
            get {
                return ResourceManager.GetString("FindAndReplaceForm_String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (selection only).
        /// </summary>
        internal static string FindAndReplaceForm_String8 {
            get {
                return ResourceManager.GetString("FindAndReplaceForm_String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not found.
        /// </summary>
        internal static string FindAndReplaceForm_String9 {
            get {
                return ResourceManager.GetString("FindAndReplaceForm_String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling.
        /// </summary>
        internal static string MainForm_StatusBuilding {
            get {
                return ResourceManager.GetString("MainForm_StatusBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation failed.
        /// </summary>
        internal static string MainForm_StatusCompilationFailed {
            get {
                return ResourceManager.GetString("MainForm_StatusCompilationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation succeeded.
        /// </summary>
        internal static string MainForm_StatusCompilationSucceeded {
            get {
                return ResourceManager.GetString("MainForm_StatusCompilationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger.
        /// </summary>
        internal static string MainForm_StatusDebugger {
            get {
                return ResourceManager.GetString("MainForm_StatusDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MainForm_StatusReady {
            get {
                return ResourceManager.GetString("MainForm_StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable file &quot;{0}&quot; not found.
        /// </summary>
        internal static string MainForm_String1 {
            get {
                return ResourceManager.GetString("MainForm_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string MainForm_String11 {
            get {
                return ResourceManager.GetString("MainForm_String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to communicate properly with the debugger: &quot;{0}&quot;. Please check that the -g flag (generate debug information) is set in the compiler options. This error could also be caused by an incompatible gdb version. Ensure that you are using version 6.x..
        /// </summary>
        internal static string MainForm_String12 {
            get {
                return ResourceManager.GetString("MainForm_String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute compiler: {0}. Please check the compiler path in the application settings..
        /// </summary>
        internal static string MainForm_String14 {
            get {
                return ResourceManager.GetString("MainForm_String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is &quot;{0}&quot;. Would you like to download the latest version &quot;{1}&quot;?.
        /// </summary>
        internal static string MainForm_String15 {
            get {
                return ResourceManager.GetString("MainForm_String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have the latest version.
        /// </summary>
        internal static string MainForm_String16 {
            get {
                return ResourceManager.GetString("MainForm_String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates: &quot;{0}&quot;. Please check your internet connection.
        /// </summary>
        internal static string MainForm_String17 {
            get {
                return ResourceManager.GetString("MainForm_String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program terminated.
        /// </summary>
        internal static string MainForm_String18 {
            get {
                return ResourceManager.GetString("MainForm_String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: .
        /// </summary>
        internal static string MainForm_String19 {
            get {
                return ResourceManager.GetString("MainForm_String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col: .
        /// </summary>
        internal static string MainForm_String20 {
            get {
                return ResourceManager.GetString("MainForm_String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialise console: {0}.
        /// </summary>
        internal static string MainForm_String21 {
            get {
                return ResourceManager.GetString("MainForm_String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the document &quot;{0}&quot;?.
        /// </summary>
        internal static string MainForm_String3 {
            get {
                return ResourceManager.GetString("MainForm_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not found.
        /// </summary>
        internal static string MainForm_String4 {
            get {
                return ResourceManager.GetString("MainForm_String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start &quot;{0}&quot;.
        /// </summary>
        internal static string MainForm_String6 {
            get {
                return ResourceManager.GetString("MainForm_String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string MainForm_String7 {
            get {
                return ResourceManager.GetString("MainForm_String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute debugger &quot;{0}&quot;: {1}..
        /// </summary>
        internal static string MainForm_String8 {
            get {
                return ResourceManager.GetString("MainForm_String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging failed for file &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string MainForm_String9 {
            get {
                return ResourceManager.GetString("MainForm_String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string SettingsAdapter_String15 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show splash screen.
        /// </summary>
        internal static string SettingsAdapter_String16 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsAdapter_String17 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string SettingsAdapter_String18 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs and spaces.
        /// </summary>
        internal static string SettingsAdapter_String19 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show line numbers.
        /// </summary>
        internal static string SettingsAdapter_String20 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show line changes.
        /// </summary>
        internal static string SettingsAdapter_String21 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight current line.
        /// </summary>
        internal static string SettingsAdapter_String22 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight matching brackets.
        /// </summary>
        internal static string SettingsAdapter_String23 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs size.
        /// </summary>
        internal static string SettingsAdapter_String24 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string SettingsAdapter_String25 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler.
        /// </summary>
        internal static string SettingsAdapter_String26 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler path.
        /// </summary>
        internal static string SettingsAdapter_String27 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of &quot;fpc.exe&quot; executable.
        /// </summary>
        internal static string SettingsAdapter_String28 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger path.
        /// </summary>
        internal static string SettingsAdapter_String29 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of &quot;gdb.exe&quot; executable.
        /// </summary>
        internal static string SettingsAdapter_String30 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreePascal compiler flags.
        /// </summary>
        internal static string SettingsAdapter_String31 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult the FreePascal manual for details. The -gp -vb flags are required by PAME for proper operation. The -Fr flag specifies the compiler error messages file. You can remove this if you want English by default..
        /// </summary>
        internal static string SettingsAdapter_String32 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution console.
        /// </summary>
        internal static string SettingsAdapter_String33 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string SettingsAdapter_String34 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground color.
        /// </summary>
        internal static string SettingsAdapter_String35 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console codepage.
        /// </summary>
        internal static string SettingsAdapter_String36 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1250 (Central Europe), 1251 (Cyrillic), 1252 (Latin I), 1253 (Greek), 1254 (Turkish), 1255 (Hebrew), 1256 (Arabic), 1257 (Baltic), 1258 (Vietnam), 874 (Thai).
        /// </summary>
        internal static string SettingsAdapter_String37 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topmost debug console.
        /// </summary>
        internal static string SettingsAdapter_String38 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger.
        /// </summary>
        internal static string SettingsAdapter_String39 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this change to take effect you have to restart PAME.
        /// </summary>
        internal static string SettingsAdapter_String40 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch variables while debugging.
        /// </summary>
        internal static string SettingsAdapter_String41 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code folding.
        /// </summary>
        internal static string SettingsAdapter_String42 {
            get {
                return ResourceManager.GetString("SettingsAdapter_String42", resourceCulture);
            }
        }
    }
}
